### ISSUE TITLE
Check return codes everywhere

### ISSUE THREAD

**Issue by elfring** [ericfischer/json-pull#1]
Would you like to add more error handling for return values from functions like the following?
- [malloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html) ⇒ [fabricate_object](https://github.com/ericfischer/json-pull/blob/6d58b770fdfe43c9d3da66de3def46844515edb9/jsonpull.c#L95)
- [printf](http://pubs.opengroup.org/onlinepubs/9699919799/functions/printf.html) ⇒ [json_print_one](https://github.com/ericfischer/json-pull/blob/8e611971270cf31ebb6a7379c9fd9573e8726870/jsoncat.c#L16)

**Comment by e-n-f** [comment]
Fixed long ago
